ALTER TABLE sales
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

UPDATE sales
SET updated_at = NOW()
WHERE updated_at IS NULL;

ALTER TABLE sales
  ALTER COLUMN updated_at SET DEFAULT NOW();
